#!/bin/bash

# usage: script/bundle PixelEditor < master.json > bundle.js
# 1st arg is name, stdio to read a json package and write the bundle

node ./dist/convert.js < /dev/stdin \
| browserify \
  --standalone "$1" \
  --ignore-missing \
  - \
